apiVersion: v1
kind: Pod
metadata:
  name: api-pod
spec:
  containers:
    - name: simple-node-api
      image: finthos/simple-node-api
      env:
        - name: PORT
          value: '8080'
      resources:
        requests:
          cpu: 100m
          memory: 128M
        limits:
          cpu: 250m
          memory: 256M
      ports:
      - containerPort: 2345
