apiVersion: v1
kind: Pod
metadata:
  name: simple-api-pod
  labels:
    app: simple-api
spec:
  containers:
    - name: simple-node-api
      image: finthos/simple-node-api
      ports:
      - containerPort: 2345
        name: 'porta-api'
